# Generated by Django 5.0.1 on 2024-01-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
